name: Example workflow
on: [push]
jobs:
  example:
    name: Example Minikube-Kubernetes Cluster interaction
    runs-on: ubuntu-latest
    outputs:
     output1: ${{ steps.step1.outputs.step1 }}
 
    steps:
    - uses: actions/checkout@v2
    - name: Start depoloyment
      id: step1
      run: |
           echo "Start on step1=$(date '+%s')" >> $GITHUB_OUTPUT
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Try the cluster !
      run: |
           kubectl get pods -A >> report.log 
           kubectl version --short >> report.log
    - name: Finish deployment
      run: |
           echo "The time elapsed:$(($(date '+%s')-${{ steps.step1.outputs.step1 }})) seconds" >> report.log
    - name: Upload report
      uses: actions/upload-artifact@v3
      with:
        path: report.log

