name: Deployment Minikube and KinD
on: [push]
jobs:
  deploy_minikube:
    name: Deployment Minikube-Kubernetes Cluster
    runs-on: ubuntu-latest
    outputs:
     output1: ${{ steps.step1.outputs.step1 }}
    steps:
    - uses: actions/checkout@v2
    - name: Start depoloyment
      id: step1
      run: |
           echo "step1=$(date '+%s')" >> $GITHUB_OUTPUT
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Try the cluster !
      run: |
           echo "Amount of pods: $(kubectl get pods -A)" >> report.log 
           echo "Version of minikube: $(kubectl version --short)" >> report.log
    - name: Average time for deployment
      run: |
           echo "Average time for deployment: $(($(date '+%s')-${{ steps.step1.outputs.step1 }})) seconds" >> report.log
  deploy_kinD:
    needs: deploy_minikube
    runs-on: ubuntu-latest
    outputs:
     output2: ${{ steps.step2.outputs.step2 }}
    steps:
       - name: Start deployment KinD
         id: step2
         run: | 
              echo "step2=$(date '+%s')" >> GITHUB_OUTPUT
       - name: Start Kind
         uses: engineerd/setup-kind@v0.5.0
         with:
          version: "v0.11.1"
       - name: Testing
         run: |
                echo "Kube version: $(kubectl version --short)" >> report.log
                echo "Amount of nodes: $(kubectl get nodes -A)" >> report.log
       - name: Average time for deployment
         run: |
           echo "Average time for deployment: $(($(date '+%s')-${{ steps.step2.outputs.step2 }})) seconds" >> report.log
    
       - name: Upload report
         uses: actions/upload-artifact@v3
         with:
          path: report.log

