name: Example workflow
on: [push]
jobs:
  example:
    name: Example Minikube-Kubernetes Cluster interaction
    runs-on: ubuntu-latest
    outputs:
     output1: ${{ steps.step1.outputs.step1 }}
    steps:
    - uses: actions/checkout@v2
    - name: Start depoloyment
      id: step1
      run: |
           echo "step1=$(date '+%s')" >> $GITHUB_OUTPUT
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Try the cluster !
      run: |
           echo "Amount of pods: \n$(kubectl get pods -A)" >> report.log 
           echo "Version of minikube: \n$(kubectl version --short)" >> report.log
    - name: Finish deployment
      run: |
           echo "Time for start cluster: \n$(($(date '+%s')-${{ steps.step1.outputs.step1 }})) seconds" >> report.log
    - name: Upload report
      uses: actions/upload-artifact@v3
      with:
        path: report.log

