name: Example workflow
on: [push]
jobs:
  example:
    name: Example Minikube-Kubernetes Cluster interaction
    runs-on: ubuntu-latest
    outputs:
     output1: ${{ steps.step1.outputs.step1 }}
     output2: ${{ steps.step2.outputs.step2 }}
    steps:
    - uses: actions/checkout@v2
    - name: Start depoloyment
      id: step1
      run: |
           echo Start on "$(date "+%Y-%m-%d %H:%M:%S")"
           echo -e "Start on step1=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Try the cluster !
      run: |
           kubectl get pods -A 
           kubectl version --short
    - name: Finish deployment
      id: step2
      run: |
           echo Finish on "$(date "+%Y-%m-%d %H:%M:%S")"
           echo -e "Finish on step2=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_OUTPUT
    - name: Result
      run: echo ${{ steps.step1.outputs.step1}} ${{ steps.step2.outputs.step2}}

